apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi-backend
  template:
    metadata:
      labels:
        app: testapi-backend
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: api-server
          image: testapi.azurecr.io/test-api:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: test-api
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '3000'
            - name: LOG_LEVEL
              value: info
            - name: SESSION_MAX_AGE_DAYS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SESSION_MAX_AGE_DAYS
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: FIREBASE_PRIVATE_KEY
          resources:
            limits:
              memory: '256Mi'
              # Sửa từ 500m xuống 250m hoặc 100m
              cpu: '100m'
            requests:
              # Thêm dòng này (hoặc sửa nếu có) để K8s dễ xếp lịch hơn
              cpu: '50m'
              memory: '128Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: testapi-backend
  ports:
    - port: 80 # Cổng nội bộ trong Cluster
      targetPort: 3000 # Cổng Node.js đang lắng nghe
